openapi: 3.1.0
info:
  title: http-api Admin Issues API
  version: '1.0'
  summary: The Precog admin HTTP REST API.
  description: The Precog admin HTTP REST API.
  contact:
    url: https://precog.com
    email: support@precog.com
servers:
- url: http://localhost:30000
security:
- BearerAuth: []
tags:
- name: Issues
paths:
  /issues/:
    post:
      summary: Create issue
      operationId: post-issues
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                required:
                - id
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - properties:
                  category:
                    type: string
                    enum:
                    - data
                  pipelineId:
                    type: string
                  datasetId:
                    type: string
                  description:
                    oneOf:
                    - properties:
                        type:
                          type: string
                          enum:
                          - missingRows
                          - duplicateRows
                      required:
                      - type
                    - properties:
                        type:
                          type: string
                          enum:
                          - missingColumns
                        names:
                          type: array
                          minItems: 1
                          uniqueItems: true
                          items:
                            type: string
                      required:
                      - type
                      - names
                    type: object
                required:
                - category
                - pipelineId
                - datasetId
                - description
              - properties:
                  category:
                    type: string
                    enum:
                    - dataset-request
                  kindId:
                    type: string
                    minLength: 1
                  docsURL:
                    type: string
                  usecase:
                    type: string
                  datasets:
                    type: array
                    uniqueItems: true
                    items:
                      type: string
                required:
                - category
                - kindId
                - usecase
                - datasets
              - properties:
                  category:
                    type: string
                    enum:
                    - source-request
                  productName:
                    type: string
                  productURL:
                    type: string
                  loginURL:
                    type: string
                  docsURL:
                    type: string
                  credentials:
                    type: string
                  usecase:
                    type: string
                  datasets:
                    type: array
                    uniqueItems: true
                    items:
                      type: string
                required:
                - category
                - productName
                - productURL
                - loginURL
                - credentials
                - usecase
                - datasets
              type: object
        description: ''
      description: Creates a new issue for engineering to look into
      tags:
      - Issues
  /issues/{issue-id}/assets:
    parameters:
    - schema:
        type: string
      name: issue-id
      in: path
      required: true
    post:
      summary: Attach asset to issue
      operationId: post-issues-issue-id-assets
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '401':
          description: Unauthorized
      description: Attaches an asset to an issue - data examples, screenshots, etc.
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties: {}
        description: Uploaded file data. Content-Type and Filename headers are required in the file data.
      tags:
      - Issues
  /issues/{issue-id}/respond:
    parameters:
    - schema:
        type: string
      name: issue-id
      in: path
      required: true
    put:
      summary: Respond to issue
      operationId: put-issues-issue-id-respond
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '401':
          description: Unauthorized
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                response:
                  type: string
              required:
              - response
        description: ''
      description: Marks an issue as having been responded to by an engineer.
      tags:
      - Issues
  /issues/{issue-id}/approve:
    parameters:
    - schema:
        type: string
      name: issue-id
      in: path
      required: true
    put:
      summary: Approve issue
      operationId: put-issues-issue-id-approve
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error-message'
        '401':
          description: Unauthorized
      description: Marks an issue resolution as accepted by the customer.
      tags:
      - Issues
components:
  schemas:
    error-message:
      title: error-message
      type: object
      properties:
        error:
          type: object
          required:
          - type
          - details
          properties:
            type:
              type: string
              minLength: 1
            details:
              type: string
      required:
      - error
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
